# -*- coding: utf-8 -*-
"""python program

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k4xQwzkUatjBKanBQ3lSYk2dbtEGxYI9
"""

i=input()
n='aeiouAEIOU'
if i in n:
    print('entered charactered is vovel')
else:
    print('entered charactered is  not vovel')

"""# New Section"""



def check_number(n):
    if n % 2 != 0:
        print("WEIRD")
    elif n % 2 == 0:
        if 2 <= n <= 5:
            print("NOT WEIRD")
        elif 6 <= n <= 20:
            print("WEIRD")
        elif n > 20:
            print("NOT WEIRD")


n = int(input("Enter a positive integer: "))


if n > 0:
    check_number(n)
else:
    print("Please enter a positive integer.")

def calculate_fee(days):
    if days <= 5:
        fee = days * 2
    elif 6 <= days <= 10:
        fee = (5 * 2) + (days - 5) * 3
    elif 11 <= days <= 15:
        fee = (5 * 2) + (5 * 3) + (days - 10) * 4
    else:
        fee = (5 * 2) + (5 * 3) + (5 * 4) + (days - 15) * 5
    return fee

days = int(input("Enter the number of days the book was used: "))


if days > 0:
    total_fee = calculate_fee(days)
    print(f"The total fee for {days} days is: Rs. {total_fee}")
else:
    print("Please enter a positive number of days.")